### ISSUE TITLE
Enable Firefox in test-ui stage

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/micro#1]
Making use of advanced user interactions fails in Firefox with `remote error: UnsupportedOperationError: mouseMoveTo`. This problem is addressed both for the [Selenium Node.js client](https://github.com/SeleniumHQ/selenium/issues/4564) and the [Selenium server](https://github.com/SeleniumHQ/selenium/issues/3693).

There is an [experimental branch](https://github.com/noyainrain/micro/tree/ui-test-w3c-actions) using a pre-release version of the client library.

On the server side, the problem should be fixed in Selenium 3.5+, but Sauce does not yet support it in combination with Firefox (test starts, then times out).

Travis CI config to enable Firefox:

```yaml
jobs:
    include:
        - <<: *test-ui
          env: BROWSER=firefox PLATFORM="Windows 10"
```
